spring:
  application:
    name: cqrs-read
  cloud:
    stream:
       kafka:
         binder:
           brokers:
             - localhost:9092
             - localhost:9096
             - localhost:9010
       bindings:
         event-consumer:
           contentType: application/json
           destination: cqrs_demo
           group: cqrs_read
  data:
    cassandra:
      keyspace-name: cqrs_read
      cluster-name: customer_x
      contact-points:
        - localhost
      port: 9042